### ISSUE TITLE
[Feature Request] chacha20 easy use supports

### ISSUE THREAD

**Issue by vay3t** [D3Ext/maldev#2]
**Describe the bug**
using modern ciphers makes detection in some antivirus more difficult, one of them is the general use of chacha20, maybe it is useful to have the ease of use like in this project https://github.com/alinz/crypto.go but to the library you are programming.

**Comment by D3Ext** [comment]
Thank you for your idea. I'll try to implement it as soon as possible.

**Comment by D3Ext** [comment]
Hi!

I've added ChaCha20 encrypt and decrypt function like in [https://github.com/alinz/crypto.go](https://github.com/alinz/crypto.go). Let me know if it works for you

This is an example:

```go
package main

import (
  "fmt"
  "log"
  "github.com/D3Ext/maldev/crypto"
)

func main(){
  data := []byte("this is an example")
  psk := []byte("ThisIsMySuperSecret32Password123")

  fmt.Println("Data:", string(data))
  fmt.Println("Key:", psk)

  ciphertext, err := crypto.Chacha20Encrypt(data, psk) // Encrypt
  if err != nil {
    log.Fatal(err)
  }

  fmt.Println("Ciphertext:", ciphertext)

  decoded, err := crypto.Chacha20Decrypt(ciphertext, psk) // Decrypt
  if err != nil {
    log.Fatal(err)
  }

  fmt.Println("Decoded:", string(decoded))
}
```

Tell me more modern ciphers and I'll add them
